### ISSUE TITLE
binary framework pod support

### ISSUE THREAD

**Issue by sunwei415** [Ruenzuo/cocoapods-amimono#17]
After using amimono, I need to manually add Pods with binary framework.

Any workaround for this?

**Comment by Ruenzuo** [comment]
I didn't look into this further, because we're using this plugin with the `!use_frameworks` flag which is required for Pods that either contain Swift and binary frameworks in transitive dependencies is not supported by CocoaPods at the moment (when you use that flag).
Now, for this plugin, it should be possible to ignore the binary frameworks [while creating the filelist](https://github.com/Ruenzuo/cocoapods-amimono/blob/master/lib/cocoapods-amimono/integrator.rb#L81-L94) by [checking if the target has to be built](https://github.com/Ruenzuo/cocoapods-amimono/blob/master/lib/cocoapods-amimono/integrator.rb#L81-L94). Maybe that's a good starting point to implement that feature.

**Comment by sunwei415** [comment]
Thank you for the quick reply.

Great that integrating binary Pods is feasible by further implementing. 

 Since I am not an experienced Ruby developer, it would be really helpful if you can share the tools and basic work flows while you are creating this great cocoapods plugin.  I will send out pull request when its done.

**Comment by Ruenzuo** [comment]
This should be supported in v0.0.8, check https://github.com/Ruenzuo/cocoapods-amimono-example/pull/1 for an example of how this works.
