### ISSUE TITLE
App rejected by Apple automatic review due to missing frameworks

### ISSUE THREAD

**Issue by igor-makarov** [Ruenzuo/cocoapods-amimono#32]
After getting all the project tests to run and uploading a build to TF, I received an email saying that the bundle does not contain some of the frameworks referenced. 

It appears that the patched `.xcconfig` files still link against the vendored frameworks like TwitterKot, but the final bundle does not contain them. 

I tried hacking it some more but I don't know how to get the linker to copy the symbols from vendored frameworks to the final target. Moreover, I don't even understand how it manages to run locally and on a device. 

If copying the vendored frameworks inline would prove impossible, I think another solution would be to have them copied over in the usual CP step. 

Unfortunately, I don't have enough time to invest in this endeavor, since I've realized that in my project's case, most of the pre-main load penalty is due to the large number of small classes (that are generated by thrift 😂).

**Comment by noremac** [comment]
I'm having the same issue, also seemingly due to an issue with vendored frameworks. I've attached a sample project. In this sample project, having _only_ a vendored framework doesn't seem to compile, but if you add a non-vendored cocoapod, things begin to compile again.

[Vendored.zip](https://github.com/Ruenzuo/cocoapods-amimono/files/989980/Vendored.zip)
